services:
  redlib:
    image: quay.io/redlib/redlib:latest
    restart: unless-stopped
    container_name: redlib
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    env_file: .env
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8080/settings"]
      interval: 5m
      timeout: 3s

  cloudflared:
    container_name: redlib_cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file: .env
    depends_on:
      - redlib
