services:
  forgejo:
    container_name: forgejo
    image: codeberg.org/forgejo/forgejo:10.0.1
    volumes:
      - ${FORGEJO_STORAGE}/data/gitea:/data/gitea
      - ${FORGEJO_STORAGE}/data/git:/data/git
      - ${FORGEJO_STORAGE}/data/ssh:/data/ssh
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: su - git -c "forgejo doctor check --all" || exit 1
      interval: 5m
      start_interval: 2m
      start_period: 30s
    depends_on:
      - postgres

  postgres:
    container_name: forgejo_db
    image: postgres:17-alpine
    volumes:
      - ${FORGEJO_STORAGE}/db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m

  cloudflared:
    container_name: forgejo_cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .env
    environment:
      TUNNEL_METRICS: '127.0.0.1:61616'
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "--metrics", "localhost:61616", "ready"]
    depends_on:
      - forgejo
